language: node_js
node_js:
  - "node"
sudo: required
before_install:
  - npm install -g node-gyp
  - npm install -g mocha
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
